# Automatische Updates für Abhängigkeiten (wöchentlich, gebündelt)
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups:
      dev-dependencies: { dependency-type: development }
      runtime-dependencies: { dependency-type: production }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /
    schedule: { interval: weekly }
